CREATE TABLE IF NOT EXISTS contact_submissions (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(254) NOT NULL,
    phone VARCHAR(40) NULL,
    topic VARCHAR(120) NOT NULL,
    message TEXT NOT NULL,
    locale CHAR(2) NOT NULL DEFAULT 'de',
    privacy_consent_version VARCHAR(32) NOT NULL,
    privacy_consent_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    newsletter_requested TINYINT(1) NOT NULL DEFAULT 0,
    newsletter_status VARCHAR(24) NOT NULL DEFAULT 'not_requested',
    notification_status VARCHAR(24) NOT NULL DEFAULT 'pending',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    INDEX contact_email_idx (email),
    INDEX contact_created_at_idx (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS event_registrations (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    event_key VARCHAR(80) NOT NULL,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(254) NOT NULL,
    locale CHAR(2) NOT NULL DEFAULT 'de',
    privacy_consent_version VARCHAR(32) NOT NULL,
    privacy_consent_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    newsletter_requested TINYINT(1) NOT NULL DEFAULT 0,
    newsletter_status VARCHAR(24) NOT NULL DEFAULT 'not_requested',
    notification_status VARCHAR(24) NOT NULL DEFAULT 'pending',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY event_email_unique (event_key, email),
    INDEX event_created_at_idx (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS newsletter_subscribers (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(254) NOT NULL,
    locale CHAR(2) NOT NULL DEFAULT 'de',
    status VARCHAR(24) NOT NULL DEFAULT 'pending',
    source VARCHAR(80) NOT NULL,
    consent_text_version VARCHAR(32) NOT NULL,
    requested_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    confirmation_token_hash CHAR(64) NULL,
    confirmation_expires_at DATETIME NULL,
    confirmed_at DATETIME NULL,
    unsubscribed_at DATETIME NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY newsletter_email_unique (email),
    INDEX newsletter_status_idx (status),
    INDEX newsletter_requested_at_idx (requested_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS members (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(254) NOT NULL,
    password_hash VARCHAR(255) NULL,
    password_set_at DATETIME NULL,
    locale CHAR(2) NOT NULL DEFAULT 'de',
    role VARCHAR(24) NOT NULL DEFAULT 'member',
    membership_tier VARCHAR(24) NOT NULL DEFAULT 'free',
    premium_expires_at DATETIME NULL,
    acquisition_source VARCHAR(80) NULL,
    acquisition_medium VARCHAR(80) NULL,
    acquisition_campaign VARCHAR(120) NULL,
    acquisition_content VARCHAR(120) NULL,
    acquisition_term VARCHAR(120) NULL,
    acquisition_landing_path VARCHAR(255) NULL,
    acquisition_referrer_host VARCHAR(160) NULL,
    acquisition_session_id CHAR(36) NULL,
    status VARCHAR(24) NOT NULL DEFAULT 'pending',
    privacy_consent_version VARCHAR(32) NOT NULL,
    privacy_consent_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    verified_at DATETIME NULL,
    last_login_at DATETIME NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY members_email_unique (email),
    INDEX members_status_idx (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS member_access_tokens (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    member_id BIGINT UNSIGNED NOT NULL,
    token_hash CHAR(64) NOT NULL,
    pending_password_hash VARCHAR(255) NULL,
    expires_at DATETIME NOT NULL,
    used_at DATETIME NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY member_access_token_unique (token_hash),
    INDEX member_access_member_idx (member_id),
    INDEX member_access_expires_idx (expires_at),
    CONSTRAINT member_access_member_fk FOREIGN KEY (member_id) REFERENCES members(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS member_sessions (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    member_id BIGINT UNSIGNED NOT NULL,
    token_hash CHAR(64) NOT NULL,
    expires_at DATETIME NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_seen_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY member_session_token_unique (token_hash),
    INDEX member_session_member_idx (member_id),
    INDEX member_session_expires_idx (expires_at),
    CONSTRAINT member_session_member_fk FOREIGN KEY (member_id) REFERENCES members(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS member_password_reset_tokens (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    member_id BIGINT UNSIGNED NOT NULL,
    token_hash CHAR(64) NOT NULL,
    expires_at DATETIME NOT NULL,
    used_at DATETIME NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY member_password_reset_token_unique (token_hash),
    INDEX member_password_reset_member_idx (member_id),
    INDEX member_password_reset_expires_idx (expires_at),
    CONSTRAINT member_password_reset_member_fk FOREIGN KEY (member_id) REFERENCES members(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS member_content_state (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    member_id BIGINT UNSIGNED NOT NULL,
    content_key VARCHAR(80) NOT NULL,
    is_favorite TINYINT(1) NOT NULL DEFAULT 0,
    progress_state VARCHAR(24) NOT NULL DEFAULT 'new',
    last_opened_at DATETIME NULL,
    completed_at DATETIME NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY member_content_unique (member_id, content_key),
    INDEX member_content_member_idx (member_id),
    INDEX member_content_updated_idx (updated_at),
    CONSTRAINT member_content_member_fk FOREIGN KEY (member_id) REFERENCES members(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS funnel_events (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    funnel_session_id CHAR(36) NOT NULL,
    event_name VARCHAR(48) NOT NULL,
    event_key VARCHAR(120) NOT NULL DEFAULT 'default',
    pathname VARCHAR(255) NULL,
    locale CHAR(2) NOT NULL DEFAULT 'de',
    utm_source VARCHAR(80) NULL,
    utm_medium VARCHAR(80) NULL,
    utm_campaign VARCHAR(120) NULL,
    utm_content VARCHAR(120) NULL,
    utm_term VARCHAR(120) NULL,
    referrer_host VARCHAR(160) NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY funnel_event_unique (funnel_session_id, event_name, event_key),
    INDEX funnel_event_created_idx (created_at),
    INDEX funnel_event_source_idx (utm_source, utm_campaign)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS cms_content_entries (
    content_key VARCHAR(160) NOT NULL,
    draft_de LONGTEXT NULL,
    draft_tr LONGTEXT NULL,
    published_de LONGTEXT NULL,
    published_tr LONGTEXT NULL,
    updated_by BIGINT UNSIGNED NULL,
    published_by BIGINT UNSIGNED NULL,
    published_at DATETIME NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (content_key),
    INDEX cms_content_updated_idx (updated_at),
    INDEX cms_content_published_idx (published_at),
    CONSTRAINT cms_content_updated_member_fk FOREIGN KEY (updated_by) REFERENCES members(id) ON DELETE SET NULL,
    CONSTRAINT cms_content_published_member_fk FOREIGN KEY (published_by) REFERENCES members(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS cms_content_revisions (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    content_key VARCHAR(160) NOT NULL,
    value_de LONGTEXT NULL,
    value_tr LONGTEXT NULL,
    published_by BIGINT UNSIGNED NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    INDEX cms_revision_content_idx (content_key, created_at),
    CONSTRAINT cms_revision_content_fk FOREIGN KEY (content_key) REFERENCES cms_content_entries(content_key) ON DELETE CASCADE,
    CONSTRAINT cms_revision_member_fk FOREIGN KEY (published_by) REFERENCES members(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS programs (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    slug VARCHAR(80) NOT NULL,
    title VARCHAR(160) NOT NULL,
    subtitle VARCHAR(600) NOT NULL,
    start_date DATE NOT NULL,
    duration_weeks SMALLINT UNSIGNED NOT NULL DEFAULT 8,
    status VARCHAR(24) NOT NULL DEFAULT 'draft',
    whatsapp_url VARCHAR(500) NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY programs_slug_unique (slug),
    INDEX programs_status_idx (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS program_weeks (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    program_id BIGINT UNSIGNED NOT NULL,
    week_number SMALLINT UNSIGNED NOT NULL,
    draft_content LONGTEXT NOT NULL,
    published_content LONGTEXT NULL,
    published_by BIGINT UNSIGNED NULL,
    published_at DATETIME NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY program_week_unique (program_id, week_number),
    INDEX program_week_published_idx (program_id, published_at),
    CONSTRAINT program_week_program_fk FOREIGN KEY (program_id) REFERENCES programs(id) ON DELETE CASCADE,
    CONSTRAINT program_week_published_member_fk FOREIGN KEY (published_by) REFERENCES members(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS program_enrollments (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    program_id BIGINT UNSIGNED NOT NULL,
    member_id BIGINT UNSIGNED NOT NULL,
    status VARCHAR(24) NOT NULL DEFAULT 'active',
    access_ends_at DATETIME NULL,
    granted_by BIGINT UNSIGNED NULL,
    granted_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY program_enrollment_unique (program_id, member_id),
    INDEX program_enrollment_member_idx (member_id, status),
    CONSTRAINT program_enrollment_program_fk FOREIGN KEY (program_id) REFERENCES programs(id) ON DELETE CASCADE,
    CONSTRAINT program_enrollment_member_fk FOREIGN KEY (member_id) REFERENCES members(id) ON DELETE CASCADE,
    CONSTRAINT program_enrollment_granted_member_fk FOREIGN KEY (granted_by) REFERENCES members(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS program_task_state (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    member_id BIGINT UNSIGNED NOT NULL,
    program_week_id BIGINT UNSIGNED NOT NULL,
    task_key VARCHAR(60) NOT NULL,
    completed_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY program_task_state_unique (member_id, program_week_id, task_key),
    INDEX program_task_state_member_idx (member_id, updated_at),
    CONSTRAINT program_task_state_member_fk FOREIGN KEY (member_id) REFERENCES members(id) ON DELETE CASCADE,
    CONSTRAINT program_task_state_week_fk FOREIGN KEY (program_week_id) REFERENCES program_weeks(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS zepter_onboarding_submissions (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    reference_code VARCHAR(32) NOT NULL,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(254) NOT NULL,
    phone VARCHAR(40) NULL,
    topic_areas TEXT NOT NULL,
    main_topic TEXT NOT NULL,
    recent_scene TEXT NOT NULL,
    desired_change TEXT NOT NULL,
    goal_statement VARCHAR(800) NOT NULL,
    goal_score TINYINT UNSIGNED NOT NULL,
    confidence_score TINYINT UNSIGNED NOT NULL,
    trigger_description TEXT NOT NULL,
    automatic_meaning TEXT NOT NULL,
    feelings VARCHAR(800) NOT NULL,
    feeling_intensity TINYINT UNSIGNED NOT NULL,
    body_response VARCHAR(800) NULL,
    typical_response TEXT NOT NULL,
    short_term_protection TEXT NOT NULL,
    long_term_cost TEXT NOT NULL,
    pattern_frequency VARCHAR(32) NOT NULL,
    feared_consequence TEXT NOT NULL,
    exceptions_text TEXT NULL,
    identity_statement VARCHAR(800) NOT NULL,
    others_statement VARCHAR(800) NOT NULL,
    world_statement VARCHAR(800) NOT NULL,
    must_statement VARCHAR(800) NOT NULL,
    must_not_statement VARCHAR(800) NOT NULL,
    early_echo TEXT NULL,
    h01 TINYINT UNSIGNED NOT NULL,
    h02 TINYINT UNSIGNED NOT NULL,
    h03 TINYINT UNSIGNED NOT NULL,
    h04 TINYINT UNSIGNED NOT NULL,
    h05 TINYINT UNSIGNED NOT NULL,
    b01 TINYINT UNSIGNED NOT NULL,
    b02 TINYINT UNSIGNED NOT NULL,
    b03 TINYINT UNSIGNED NOT NULL,
    stability VARCHAR(24) NOT NULL,
    professional_support VARCHAR(24) NOT NULL,
    safe_support TEXT NULL,
    resources_text TEXT NOT NULL,
    crisis_contact VARCHAR(24) NOT NULL,
    consent_version VARCHAR(48) NOT NULL,
    consent_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    aggregate_consent TINYINT(1) NOT NULL DEFAULT 0,
    review_status VARCHAR(24) NOT NULL DEFAULT 'neu',
    review_note TEXT NULL,
    reviewed_by BIGINT UNSIGNED NULL,
    reviewed_at DATETIME NULL,
    confirmation_status VARCHAR(24) NOT NULL DEFAULT 'pending',
    notification_status VARCHAR(24) NOT NULL DEFAULT 'pending',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY zepter_onboarding_reference_unique (reference_code),
    INDEX zepter_onboarding_email_idx (email),
    INDEX zepter_onboarding_status_idx (review_status, created_at),
    CONSTRAINT zepter_onboarding_reviewer_fk FOREIGN KEY (reviewed_by) REFERENCES members(id) ON DELETE SET NULL,
    CONSTRAINT zepter_onboarding_goal_score_check CHECK (goal_score <= 10),
    CONSTRAINT zepter_onboarding_confidence_score_check CHECK (confidence_score <= 10),
    CONSTRAINT zepter_onboarding_feeling_intensity_check CHECK (feeling_intensity <= 10),
    CONSTRAINT zepter_onboarding_h01_check CHECK (h01 <= 10),
    CONSTRAINT zepter_onboarding_h02_check CHECK (h02 <= 10),
    CONSTRAINT zepter_onboarding_h03_check CHECK (h03 <= 10),
    CONSTRAINT zepter_onboarding_h04_check CHECK (h04 <= 10),
    CONSTRAINT zepter_onboarding_h05_check CHECK (h05 <= 10),
    CONSTRAINT zepter_onboarding_b01_check CHECK (b01 <= 10),
    CONSTRAINT zepter_onboarding_b02_check CHECK (b02 <= 10),
    CONSTRAINT zepter_onboarding_b03_check CHECK (b03 <= 10)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS zepter_schedule_surveys (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    participant_key CHAR(64) NOT NULL,
    reference_code VARCHAR(32) NOT NULL,
    name VARCHAR(100) NOT NULL,
    available_slots TEXT NOT NULL,
    preferred_slot VARCHAR(32) NOT NULL,
    known_exceptions VARCHAR(800) NULL,
    email VARCHAR(254) NULL,
    invoice_address VARCHAR(500) NULL,
    payment_choice VARCHAR(32) NULL,
    desired_installment DECIMAL(10,2) NULL,
    consent_version VARCHAR(48) NOT NULL,
    consent_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY zepter_schedule_participant_unique (participant_key),
    UNIQUE KEY zepter_schedule_reference_unique (reference_code),
    INDEX zepter_schedule_preferred_idx (preferred_slot),
    INDEX zepter_schedule_updated_idx (updated_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS ai_command_center_settings (
    id TINYINT UNSIGNED NOT NULL DEFAULT 1,
    monthly_budget_usd DECIMAL(10,2) NOT NULL DEFAULT 15.00,
    per_run_budget_usd DECIMAL(10,2) NOT NULL DEFAULT 2.00,
    external_actions_enabled TINYINT(1) NOT NULL DEFAULT 0,
    updated_by BIGINT UNSIGNED NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT ai_settings_member_fk FOREIGN KEY (updated_by) REFERENCES members(id) ON DELETE SET NULL,
    CONSTRAINT ai_settings_single_row_check CHECK (id = 1)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS ai_pilot_weeks (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    week_number TINYINT UNSIGNED NOT NULL,
    participant_count SMALLINT UNSIGNED NOT NULL,
    planned_focus VARCHAR(800) NOT NULL,
    actual_focus VARCHAR(800) NOT NULL,
    common_questions LONGTEXT NULL,
    helpful_exercises LONGTEXT NULL,
    challenges LONGTEXT NULL,
    observed_changes LONGTEXT NULL,
    professional_insights LONGTEXT NULL,
    next_adjustments LONGTEXT NULL,
    anonymization_confirmed TINYINT(1) NOT NULL DEFAULT 0,
    created_by BIGINT UNSIGNED NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY ai_pilot_week_number_unique (week_number),
    INDEX ai_pilot_updated_idx (updated_at),
    CONSTRAINT ai_pilot_member_fk FOREIGN KEY (created_by) REFERENCES members(id) ON DELETE RESTRICT,
    CONSTRAINT ai_pilot_week_number_check CHECK (week_number BETWEEN 1 AND 8)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS ai_workflow_runs (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    workflow_id VARCHAR(80) NOT NULL,
    workflow_name VARCHAR(160) NOT NULL,
    execution_mode VARCHAR(24) NOT NULL DEFAULT 'mock',
    status VARCHAR(24) NOT NULL DEFAULT 'completed',
    source_pilot_week_id BIGINT UNSIGNED NULL,
    input_json LONGTEXT NOT NULL,
    steps_json LONGTEXT NOT NULL,
    result_json LONGTEXT NOT NULL,
    usage_json LONGTEXT NULL,
    estimated_cost_usd DECIMAL(10,4) NOT NULL DEFAULT 0,
    actual_cost_usd DECIMAL(10,4) NOT NULL DEFAULT 0,
    approval_status VARCHAR(24) NOT NULL DEFAULT 'pending',
    error_message VARCHAR(500) NULL,
    decision_note TEXT NULL,
    decided_by BIGINT UNSIGNED NULL,
    decided_at DATETIME NULL,
    created_by BIGINT UNSIGNED NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    completed_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    INDEX ai_run_created_idx (created_at),
    INDEX ai_run_approval_idx (approval_status, created_at),
    CONSTRAINT ai_run_pilot_week_fk FOREIGN KEY (source_pilot_week_id) REFERENCES ai_pilot_weeks(id) ON DELETE SET NULL,
    CONSTRAINT ai_run_creator_fk FOREIGN KEY (created_by) REFERENCES members(id) ON DELETE RESTRICT,
    CONSTRAINT ai_run_decider_fk FOREIGN KEY (decided_by) REFERENCES members(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS ai_generated_assets (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    source_run_id BIGINT UNSIGNED NOT NULL,
    brief_index TINYINT UNSIGNED NOT NULL,
    provider VARCHAR(40) NOT NULL DEFAULT 'OpenAI',
    model VARCHAR(80) NOT NULL,
    prompt TEXT NOT NULL,
    mime_type VARCHAR(80) NOT NULL DEFAULT 'image/png',
    image_data LONGBLOB NULL,
    image_size VARCHAR(40) NOT NULL,
    image_quality VARCHAR(24) NOT NULL,
    status VARCHAR(24) NOT NULL DEFAULT 'running',
    estimated_cost_usd DECIMAL(10,4) NOT NULL DEFAULT 0,
    actual_cost_usd DECIMAL(10,4) NOT NULL DEFAULT 0,
    error_message VARCHAR(500) NULL,
    created_by BIGINT UNSIGNED NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    completed_at DATETIME NULL,
    PRIMARY KEY (id),
    INDEX ai_asset_source_idx (source_run_id, created_at),
    INDEX ai_asset_created_idx (created_at),
    CONSTRAINT ai_asset_run_fk FOREIGN KEY (source_run_id) REFERENCES ai_workflow_runs(id) ON DELETE CASCADE,
    CONSTRAINT ai_asset_creator_fk FOREIGN KEY (created_by) REFERENCES members(id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
