// Turkish copy proofread by Selcan for the Berlin Live landing page.
// This content is intentionally isolated from the disabled global language switch.

export const berlinLiveTurkishDefaults = Object.freeze({
  "hero.nav-cta": "Kontenjanı gör",
  "hero.eyebrow": "Berlin’de Aile ve Sistem Dizimi · 9–10 Ekim 2026",
  "hero.title": "Berlin’de Travma Duyarlı Aile ve Sistem Dizimi",
  "hero.lead-strong": "Bilinçdışında etkisini sürdüren bağlar, roller ve sorumluluklar aile diziminde kendilerine bir yer bulur.",
  "hero.lead": "İki gün boyunca aile sistemindeki görünmeyen dinamiklere, kuşaklar boyunca tekrarlanan ilişki örüntülerine ve bugün hâlâ taşıdığınız rollere birlikte bakıyoruz. Her aile dizimine birlikte rehberlik ediyor, süreç boyunca size eşlik ediyoruz.",
  "hero.date": "9 ve 10 Ekim 2026",
  "hero.time": "Her iki gün 10.00–19.00",
  "hero.location": "Berlin · Mekân yakında açıklanacaktır",
  "hero.cta": "Katılım seçeneklerini incele",
  "hero.capacity": "• Toplam 20 kişilik grup\n• 6 kişiye kendi aile dizimini açtırma imkânı",
  "hero.image-eyebrow": "İki uzman. Birlikte yönetilen tek bir aile dizimi süreci.",
  "hero.image-text": "Aile sistemindeki dinamiği görmek, kişinin içsel tepkisini anlamak ve yaşananları birlikte anlamlandırmak.",
  "system.eyebrow": "Aile sistemine bakış",
  "system.title": "Bugün yaşadığınız bir konu, aile içinde geçmişte aldığınız bir yerle bağlantılı olabilir",
  "system.intro": "Aile diziminde bir tepkiyi yalnızca bugünkü davranış üzerinden değerlendirmeyiz. Bu tepkinin hangi ilişkiler içinde oluştuğuna, kişinin aile sisteminde hangi rolü üstlendiğine ve geçmişte gerekli olan bu rolün bugün hâlâ yaşamını etkileyip etkilemediğine bakarız.",
  "system.note": "Buradaki amaç suçlu bulmak değildir. Aidiyetin, sorumluluğun ve bağlılığın kişinin içsel aile tablosunda nasıl düzenlendiğini anlamaktır.",
  "system.item-1-eyebrow": "Aidiyet ve dışlanma",
  "system.item-1-title": "Ailede yeri görülmeyen biri, sistem üzerinde güçlü bir etkiye sahip olmaya devam edebilir",
  "system.item-1-text": "Aile sistemine yalnızca bugün birlikte olduğumuz kişiler dâhil değildir. Erken yaşta hayatını kaybedenler, aileden ayrılan veya dışlanan kişiler, önceki eşler, düşükler, kayıplar, ayrılıklar ve aniden kesilen ilişkiler de aile sisteminde bir yere sahiptir. Bir kişinin veya olayın hikâyesine aile içinde yer verilmediğinde, sonraki kuşaklardan biri nedenini bilmeden bu boşluğa yönelebilir. Aile diziminde kimin görülmediği, kimin bakışının geçmişte kaldığı ve hangi bağlılığın kişinin kendi yaşamını sürdürmesini zorlaştırdığı görünür hâle gelebilir. Böylece geçmişi reddetmeden kendi hikâyenizi yazabileceğiniz yeni bir yer oluşabilir.",
  "system.item-2-eyebrow": "Roller ve sorumluluklar",
  "system.item-2-title": "Bir çocuk çok erken yaşta arabulucu, sırdaş veya ailenin dayanağı olduğunda",
  "system.item-2-text": "Çocuklar bağlılığı ve aile içindeki güveni korumaya çalışır. Anne ve babasının arasında arabuluculuk yapabilir, kardeşlerinin sorumluluğunu üstlenebilir, bir yetişkinin duygusal yükünü taşıyabilir veya kendi ihtiyaçlarını geri plana atabilir. Çocuklukta aileyi bir arada tutmaya yardımcı olan bu rol, yetişkinlikte aşırı sorumluluk, sürekli tetikte olma, sınır koyduğunda suçluluk duyma veya başkalarının iyiliğinden kendini sorumlu görme biçiminde devam edebilir. Aile dizimi, kuşaklar arasındaki düzenin nerede değiştiğini ve taşınan bir sorumluluğun aslında kime ait olduğunu görünür hâle getirebilir. Böylece kişi kendisine ait olmayan sorumluluğu ait olduğu yere bırakabilir ve kendi yaşamında daha özgür bir yer alabilir.",
  "system.item-3-eyebrow": "Aileye bağlılık ve kendi yolunu seçmek",
  "system.item-3-title": "Bazen kişinin gelişmesi, ailesine sadakatsizlik ediyormuş gibi hissettirebilir",
  "system.item-3-text": "Kendi yolunuzu seçmek, bilinçdışında ailenize olan bağlılığınızla çatışabilir. Anne ve babanızdan daha başarılı olmak, farklı bir ilişki biçimini seçmek, başka bir ülkeye taşınmak veya net bir şekilde ‘hayır’ demek doğru görünse bile içinizde huzursuzluk yaratabilir. Bu durumda yaşanan tereddüdün arkasında irade eksikliği değil, güçlü bir aidiyet sorusu bulunabilir: ‘Hayatımı farklı yaşarsam yine de aileme ait olabilir miyim?’ Aile dizimi bu bağlılığı görünür hâle getirir. Kişinin geldiği aileyi ve geçmişini onurlandırırken kendi yaşamını seçebileceği yeni bir ilişki biçimi araştırılır. Böylece görünür olmak, başarılı olmak ve kendi yolunuzu seçmek, sevdiklerinizi kaybetme korkusundan ayrılmaya başlayabilir.",
  "system.item-4-eyebrow": "Tekrarlayan ilişki örüntüleri",
  "system.item-4-title": "Bir kuşakta tamamlanmayan bir hareket, sonraki kuşakta başka bir biçimde ortaya çıkabilir",
  "system.item-4-text": "Aile örüntüleri her zaman birebir tekrarlanmaz. Bazen roller, beklentiler, ittifaklar ve sessiz görevler aracılığıyla yaşamaya devam eder. Bir kişi tekrar tekrar dışlanan konumuna düşebilir, iki taraf arasında kalabilir veya yetişkinlikteki ilişkilerinde çocukluğunda üstlendiği rolü yeniden yaşayabilir. Aile diziminde ilişkilerin mekânda görünür hâle gelmesi şu sorulara bakmamızı sağlar: Kim kime bakıyor? Kim kimin arasında duruyor? Kim sistemin dışında kalıyor? Kim kendisine ait olmayan bir gerilimi taşıyor? Bu sorular kişinin aile sistemi içindeki konumunu daha iyi anlamasına yardımcı olur. Buradan kendi yaşamına ve gelişimine doğru yeni bir hareket başlayabilir.",
  "process.eyebrow": "Bir aile dizimi sırasında neler olur?",
  "process.title": "Aile hikâyesi mekânda görünür bir tabloya dönüşür",
  "process.intro": "Bir aile dizimi, üzerinde çalışmak istediğiniz konunun netleştirilmesiyle başlar. Ardından aile üyeleri veya konuyla bağlantılı unsurlar için temsilciler seçilir ve mekânda belirli yerlere yerleştirilir. Bir aile dizimi çalışması bizde yaklaşık 90 dakika sürer. Her dizime birlikte rehberlik eder, süreci iki farklı uzmanlık alanından birlikte yönetiriz.",
  "process.image-note": "Çalışmaya yalnızca güncel konu için gerekli olan aile bilgileri dâhil edilir. Bütün aile geçmişinizi anlatmanız gerekmez. Köken aileniz, bugünkü aileniz, önceki ilişkiler, kayıplar, ayrılıklar ve hayatınız üzerinde etkili olan roller gerektiği ölçüde sürece alınabilir.",
  "process.step-1-title": "Çalışılacak konu netleştirilir",
  "process.step-1-text": "Büyük ve genel bir konudan, aile diziminde bakılabilecek somut bir soruya ulaşılır. ‘Bütün ailem’ dizilmez. Bugün hayatınızı etkileyen ilişkiye, role veya tekrarlanan dinamiğe odaklanılır. Bu ilk görüşmede hangi kişilerin, olayların veya kuşakların çalışma açısından önemli olabileceği belirginleşmeye başlar.",
  "process.step-2-title": "İçsel aile tablosu mekânda kurulur",
  "process.step-2-text": "Konunuzla bağlantılı kişiler veya unsurlar için gruptan temsilciler seçersiniz ve onlara mekânda bir yer verirsiniz. Temsilcilerin birbirlerine olan uzaklıkları, bakış yönleri, beden duruşları ve sistem içindeki konumları ilk ilişki tablosunu oluşturur. Konuşurken soyut kalan bir ilişki dinamiği böylece görünür ve deneyimlenebilir hâle gelir.",
  "process.step-3-title": "Temsilciler sistemde algıladıklarını ifade eder",
  "process.step-3-text": "Temsilcilerin bir karakteri canlandırması veya oyunculuk yapması gerekmez. Bulundukları yerde algıladıkları bedensel ve duygusal tepkileri ifade ederler: yakınlık veya uzaklık, baskı veya rahatlama, birine bakma ya da uzaklaşma isteği, bedende oluşan bir duyum veya hareket etme dürtüsü. Biz bu algıları dikkatle sorar, birbirleriyle ilişkilendirir ve çalışmayı açtıran kişinin konusuyla bağlantısını koruruz. Temsilcilerin algıları mutlak gerçekler veya aile geçmişi hakkında kesin bilgiler olarak değerlendirilmez. Bunlar, süreç içinde birlikte incelenen ve anlamlandırılan ipuçlarıdır.",
  "process.step-4-title": "Daha uyumlu bir düzen araştırılır",
  "process.step-4-text": "Temsilcilerin yerleri değiştirilebilir, sistemde eksik kalan kişiler dâhil edilebilir ve sorumluluklar daha net şekilde ayrıştırılabilir. Bazen kısa bir cümle, bakış, mesafe veya yeni bir konum; herkes kendi yerini aldığında sistemde nelerin değişebileceğini hissettirir. Çalışmanın sonunda amaç kusursuz bir aile tablosu oluşturmak değildir. Amaç, üzerinde çalıştığınız konuyla ilgili yeni bir içsel yönelim ve daha geniş bir hareket alanı kazanmaktır.",
  "process.method-eyebrow": "Spirit Healing",
  "process.method-title": "Aile dizimi sürecini yalnızca dışarıda oluşan tabloyla sınırlamıyoruz",
  "process.method-text": "Çalışmanın başlangıç noktası aile sistemindeki ilişkiler ve dinamiklerdir. Dizim sırasında güçlü bir bağlılık, bedensel gerilim veya enerji alanında yoğun bir hareket ortaya çıktığında enerji algımızı ve enerji çalışmasını doğrudan sürece dâhil edebiliriz. Bu çalışma ayrı bir program bölümü değildir; aile sistemindeki ilişki görünür hâle geldiğinde, ihtiyaç duyulan yerde sürecin doğal bir parçası olarak uygulanır. Aynı anda kişinin içinde güçlü bir çatışma veya koruyucu mekanizma ortaya çıkarsa içsel parçalar çalışması da aile dizimine dâhil edilebilir. Böylece yalnızca sistemdeki dış konuma değil, kişiyi o konumda tutan içsel bağlılığa ve koruyucu parçaya da bakabiliriz. Çalışmanın odağında her zaman kişinin getirdiği ailevi konu ve bu konudan ortaya çıkan hareket bulunur.",
  "duo.eyebrow": "Ortak çalışma biçimimiz",
  "duo.title": "İki uzman. Birlikte yönetilen tek bir aile dizimi süreci.",
  "duo.intro": "Bir aile dizimi sırasında aynı anda birçok şey gerçekleşir. Temsilciler birbirlerine tepki verir, sistemdeki küçük bir hareket bütün ilişki tablosunu değiştirebilir ve kendi konusuyla çalışan kişide bedensel veya duygusal bir tepki ortaya çıkabilir. Biz aile dizimi sürecini birlikte yönetiyoruz.",
  "duo.note": "Birimiz kişinin duygusal, bedensel ve içsel tepkilerine daha yakın kalırken diğerimiz aile sisteminin tamamını, temsilcileri ve gruptaki hareketi takip edebilir. Gördüklerimizi ancak çalışma bittikten sonra bir araya getirmiyoruz; her iki bakış da aynı anda aynı sürecin içine giriyor. Böylece aile ve sistem dizimi, içsel parçalar çalışması, travma duyarlı terapötik rehberlik ve enerji çalışması birbirinden kopmadan ilerliyor. Her aile dizimine birlikte rehberlik ediyor ve çalışma boyunca kişiye birlikte eşlik ediyoruz.",
  "own.eyebrow": "Kendi aile diziminizi açtırmak",
  "own.title": "Konunun arkasındaki asıl soru yönü belirler",
  "own.intro": "Bir konu, aile sistemi içerisinde bir ilişki veya konum olarak ele alınabiliyorsa aile dizimi çalışmasına uygun olabilir. Konu köken aileniz, bugünkü aileniz, ilişkiniz veya birkaç kişi arasında üstlendiğiniz yerle bağlantılı olabilir.",
  "own.note": "Bunun için eksiksiz bir aile geçmişine sahip olmanız gerekmez. Bugünkü yaşamınızda neyin tekrarlandığı veya üzerinde çok düşünmenize rağmen hangi noktada ilerleyemediğiniz daha önemlidir. Birlikte, getirdiğiniz konuyu aile diziminde araştırılabilecek açık ve somut bir soruya dönüştürürüz.",
  "own.questions": "Köken ailemin yanına girdiğimde neden yeniden eski rolüme dönüyorum?\nBirisi hayal kırıklığına uğradığında neden sınır koymakta zorlanıyorum?\nAnne, baba, kardeşler veya ailenin iki tarafı arasındaki çatışmada hangi konumu üstlendim?\nİlişkilerimde yakınlık, geri çekilme ve sorumluluk döngüsü neden tekrar ediyor?\nBir kayıp, ayrılık veya dışlanan aile üyesiyle ilgili sistemde ne tamamlanmadan kaldı?\nAilemden farklı bir hayat yaşamamı ve kendi yerimi almamı engelleyen bağlılık nedir?",
  "group.eyebrow": "Grup da sürecin bir parçasıdır",
  "group.title": "Kendi aile diziminizi açtırmadan da çalışmanın parçası olabilirsiniz",
  "group.intro": "Grup ve temsilci katılımı bir seyirci yeri değildir. Terapötik giriş bölümüne, farkındalık çalışmalarına, bütün aile dizimlerine ve ortak değerlendirmelere dâhil olursunuz. Farklı aile hikâyeleri üzerinden sistemik roller ve ilişkiler doğrudan deneyimlenebilir hâle gelir.",
  "group.item-1-title": "Temsilci olarak bir rol oynamanız gerekmez",
  "group.item-1-text": "Bir kişi veya unsur için temsilci seçildiğinizde öncelikle yalnızca size gösterilen yerde durursunuz. Bedeninizde oluşan duyumları, bakış yönünüzü, yakınlık veya uzaklık ihtiyacınızı ve hareket dürtülerinizi gözlemlersiniz. Aile dizimi bu algılardan hareketle adım adım gelişir.",
  "group.item-2-title": "Başka birinin aile dizimi kendi konunuza dokunabilir",
  "group.item-2-text": "Kendi hikâyeniz dizilmediği hâlde tanıdığınız bir rol karşınıza çıkabilir: anne ve babası arasında kalan çocuk, herkesin yükünü taşıyan kız çocuğu, duygusal olarak ulaşılamayan baba, iki kuşak arasında kurulan ittifak veya ailede sürekli dışarıda bırakılan kişi. Yaptığımız açıklamalar ve ortak değerlendirmeler, bu hareketleri sistemik açıdan anlamanıza yardımcı olur.",
  "group.item-3-title": "Her temsilcilik için kendiniz karar verirsiniz",
  "group.item-3-text": "Bir temsilciliği kabul edebilir, reddedebilir veya çalışma sırasında bırakabilirsiniz. Hiç kimse bir rolü üstlenmeye ya da çalışma içinde kalmaya zorlanmaz. Her aile diziminin ardından temsil edilen rol bilinçli biçimde bırakılır. Grupta paylaşılan kişisel bilgiler ve yaşanan süreçler gizli tutulur.",
  "weekend.eyebrow": "İki günlük program",
  "weekend.title": "Giriş, deneyim, aile dizimleri ve entegrasyon",
  "weekend.intro": "İlk gün ortak bir terapötik ve sistemik temel oluşturuyoruz. Soruları yanıtlıyor ve ilk farkındalık çalışmalarını yapıyoruz. Ardından aile dizimi çalışmalarına başlıyoruz. İkinci gün diğer aile dizimleriyle devam ediyor ve süreci ortak bir değerlendirme ve kapanışla tamamlıyoruz. Bir çalışma daha fazla zamana ihtiyaç duyduğunda programın akışında küçük değişiklikler yapılabilir.",
  "weekend.friday-date": "9 Ekim Cuma",
  "weekend.friday-title": "Anlamak ve ilk aile dizimi",
  "weekend.friday-lines": "Terapötik ve sistemik giriş, sorular ve ilk farkındalık çalışmaları\nÖğle arası\nYaklaşık 90 dakikalık ilk aile dizimi, ortak değerlendirme ve kahve molası",
  "weekend.saturday-date": "10 Ekim Cumartesi",
  "weekend.saturday-title": "Aile dizimleri ve ortak kapanış",
  "weekend.saturday-lines": "Aile dizimi çalışmaları\nÖğle arası\nDiğer aile dizimleri, kahve molası, entegrasyon ve ortak kapanış",
  "weekend.note": "Belirtilen saatler planlanan genel çerçeveyi göstermektedir. Yoğun bir süreç daha fazla zamana ihtiyaç duyduğunda bazı bölümlerin başlangıç ve bitiş saatleri değişebilir.",
  "tickets.eyebrow": "Katılım seçenekleri",
  "tickets.title": "İki farklı katılım seçeneği",
  "tickets.intro": "Her iki katılım seçeneği de cuma ve cumartesi günlerinin tamamını kapsar. Aralarındaki tek fark, kendi konunuz için bir aile diziminin size ayrılmış olup olmamasıdır.",
  "tickets.own-label": "Kendi dizimiyle katılım",
  "tickets.own-items": "Terapötik girişe ve farkındalık çalışmalarına katılım\nBütün aile dizimlerine katılım\nKendi konunuz için ayrılmış yaklaşık 90 dakikalık aile dizimi\nSabine ve Selcan’ın birlikte yönettiği süreç\nAile diziminize iki uzman tarafından rehberlik edilmesi\nOrtak değerlendirme ve entegrasyon",
  "tickets.own-cta": "Kendi dizimle katılım için yerimi ayır",
  "tickets.intensive-label": "Grup ve temsilci katılımı",
  "tickets.intensive-items": "Terapötik girişe ve farkındalık çalışmalarına katılım\nİki gün boyunca bütün aile dizimlerine katılım\nİstediğiniz takdirde temsilci olarak aktif katılım\nSabine ve Selcan’ın birlikte yönettiği süreç\nOrtak değerlendirmeler ve entegrasyon\nKendi aile diziminizin açılması bu katılım türüne dâhil değildir",
  "tickets.intensive-cta": "Grup ve temsilci katılımı için yerimi ayır",
  "tickets.duration": "İki günün tamamı için",
  "tickets.installment-note": "İki taksitle ödeme mümkündür.",
  "tickets.installment-cta": "İki taksitle kayıt ol",
  "tickets.priority-note": "Mevcut sekiz haftalık programımızın katılımcılarına sınırlı bir süre için ön kayıt hakkı verilecektir. Ardından kalan yerler genel katılıma açılacaktır."
});

export const berlinLiveStaticTurkishTranslations = Object.freeze({
  "Zur Spirit-Healing-Startseite": "Spirit Healing ana sayfasına git",
  "Blick über Berlin bei Abendlicht": "Akşam ışığında Berlin manzarası",
  "Aufstellungsarbeit in einer Gruppe": "Grup içinde aile dizimi çalışması",
  "Sabine Schmidt und Selcan Yilmaz": "Sabine Schmidt ve Selcan Yılmaz",
  "6 Plätze": "6 kişilik kontenjan",
  "Buchung wird freigeschaltet": "Kayıt yakında açılacak",
  "14:00–ca. 19:00": "14.00–yaklaşık 19.00",
  "Impressum": "Künye",
  "Datenschutz": "Gizlilik",
  "10:00–13:00": "10.00–13.00",
  "13:00–14:00": "13.00–14.00"
});
