import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { submitForm } from "@/lib/submissions";
import { replayFunnel } from "@/content/replayFunnel";

export const LiveTalkSecond = () => {
    const [info, setInfo] = useState(null);
    const [status, setStatus] = useState("idle");
    const [error, setError] = useState("");
    useEffect(() => {
        const controller = new AbortController();
        fetch("/api/live-talk-2", { signal: controller.signal, cache: "no-store" }).then(r => r.json()).then(r => { if (!r.ok) throw new Error(); setInfo(r.event); }).catch(e => { if (e.name !== "AbortError") setError("Die Anmeldung ist gerade nicht erreichbar. Bitte versuche es später noch einmal oder schreibe an info@spirit-healing.tr."); });
        return () => controller.abort();
    }, []);
    const register = async event => {
        event.preventDefault(); if (status === "sending" || !info?.ready) return;
        const data = new FormData(event.currentTarget); setStatus("sending"); setError("");
        try {
            await submitForm("/api/live-talk-2/register", { name: data.get("name"), email: data.get("email"), company: data.get("company"), privacyConsent: data.get("privacy") === "on", newsletterConsent: data.get("newsletter") === "on" });
            setStatus("success");
        } catch (e) { setStatus("idle"); setError(e.code === "closed" ? "Die Anmeldung ist noch nicht geöffnet oder der Termin hat bereits begonnen." : e.code === "full" ? "Alle Live-Plätze sind vergeben. Für die Warteliste schreibe an info@spirit-healing.tr." : "Die Anmeldung konnte nicht gespeichert werden. Bitte prüfe deine Angaben und versuche es erneut."); }
    };
    const field = "mt-2 min-h-12 w-full rounded-xl border border-[#b9cec7] bg-white px-4 py-3 text-[#173c39]";
    return <main data-no-translate="true" className="min-h-screen bg-[#faf6ed] px-5 py-8 text-[#173c39]"><div className="mx-auto max-w-5xl"><nav className="flex flex-wrap justify-between gap-4"><Link className="font-serif text-xl" to="/">Spirit Healing</Link><Link className="underline" to={replayFunnel.path}>Zur Aufzeichnung & zum Workbook</Link></nav>
        <header className="mt-9 rounded-3xl bg-[#075d60] px-7 py-12 text-white sm:px-12"><p className="text-sm font-bold uppercase tracking-[0.17em] text-[#edcf96]">Zweiter Live-Abend · 20. Oktober · 20 Uhr</p><h1 className="mt-5 font-serif text-4xl leading-tight sm:text-6xl">Eine Stufe tiefer.<br/>Mit deinen Erfahrungen.</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-white/90">Du hast begonnen, die Anteile in deinem Alltag zu beobachten. Jetzt schauen wir gemeinsam auf das, was sich dir gezeigt hat.</p><p className="mt-6 font-semibold">Mit Sabine & Selcan · kostenlos über Zoom<br/>Dienstag, 20. Oktober 2026, 20 Uhr deutscher Zeit</p></header>
        <div className="mt-8 grid gap-8 lg:grid-cols-2"><section className="p-3 sm:p-7"><h2 className="font-serif text-3xl">Bring eine Beobachtung mit.</h2><p className="mt-5 leading-8">Vielleicht hat dich ein Satz berührt. Vielleicht hast du bemerkt, wie sich deine Stimme oder deine Körperhaltung verändert hat. Vielleicht erkennst du eine Rolle, in die du immer wieder zurückkehrst.</p><p className="mt-4 leading-8">Was hast du entdeckt? Wo hast du einen Anteil bemerkt? Was ist noch unklar? Wir holen euch bei euren Erfahrungen ab und gehen gemeinsam weiter.</p><p className="mt-4 leading-8">Auch wenn du beim ersten Abend nicht dabei warst, bist du willkommen. Die Aufzeichnung und das Workbook geben dir den Einstieg. Du musst nichts fertig bearbeitet haben.</p><Link to={replayFunnel.path} className="mt-6 inline-block font-bold underline underline-offset-4">Den ersten Vortrag kennenlernen</Link></section>
        {status === "success" ? <section role="status" className="rounded-3xl bg-white p-7 sm:p-9"><h2 className="font-serif text-3xl">Schau in dein E-Mail-Postfach.</h2><p className="mt-5 leading-8">Für eine neue Anmeldung senden wir dir in wenigen Minuten die Bestätigung mit deinem Zoom-Zugang. Bitte prüfe auch den Spam-Ordner.</p><p className="mt-4 leading-7">Du bist bereits angemeldet? Dein bisheriger Zugang zum 20. Oktober bleibt gültig. Eine erneute Anmeldung verschickt keine doppelte E-Mail. Bei Fragen schreibe an info@spirit-healing.tr.</p></section> : <form onSubmit={register} className="rounded-3xl bg-white p-7 sm:p-9"><h2 className="font-serif text-3xl">Sei live dabei.</h2><p className="mt-4 leading-7">Nach der Anmeldung erhältst du deinen Zoom-Zugang per E-Mail. Wir erinnern dich am Vortag und eine Stunde vor Beginn.</p><label className="mt-6 block font-semibold" htmlFor="second-name">Dein Vorname</label><input id="second-name" name="name" className={field} autoComplete="given-name" required maxLength={100}/><label className="mt-5 block font-semibold" htmlFor="second-email">Deine E-Mail-Adresse</label><input id="second-email" name="email" type="email" className={field} autoComplete="email" required maxLength={254}/><div className="absolute -left-[10000px]" aria-hidden="true"><label htmlFor="second-company">Firma</label><input id="second-company" name="company" tabIndex={-1} autoComplete="off"/></div><label className="mt-6 flex gap-3 text-sm leading-6"><input type="checkbox" name="privacy" required className="mt-1 h-4 w-4 shrink-0"/><span>Ich stimme der Verarbeitung meiner Angaben für die Anmeldung, den Zoom-Zugang und die Terminerinnerungen zu. <Link className="underline" to="/datenschutz">Datenschutz</Link>. Über den Link in meiner E-Mail kann ich absagen.</span></label><label className="mt-4 flex gap-3 text-sm leading-6"><input type="checkbox" name="newsletter" className="mt-1 h-4 w-4 shrink-0"/><span>Ich möchte weitere Impulse von Spirit Healing per E-Mail erhalten. Freiwillig, mit separater E-Mail-Bestätigung und jederzeit abbestellbar.</span></label>{info && !info.ready && <p role="status" className="mt-5 rounded-xl bg-[#faf6ed] p-4 leading-7">Die Anmeldung für diesen Termin ist noch nicht geöffnet oder bereits geschlossen. Die Aufzeichnung und das Workbook findest du über den Link links.</p>}{error && <p role="alert" className="mt-5 text-red-800">{error}</p>}<button disabled={!info?.ready || status === "sending"} className="mt-7 min-h-12 w-full rounded-full bg-[#075d60] px-6 py-4 font-bold text-white disabled:opacity-50">{status === "sending" ? "Anmeldung wird gespeichert …" : "Kostenlos anmelden"}</button><p className="mt-4 text-xs leading-6">Keine Newsletter-Pflicht. Die Anmeldung zum ersten Live gilt nicht automatisch für diesen zweiten Termin.</p></form>}</div>
        <footer className="mt-10 flex flex-wrap gap-6 py-6 text-sm"><Link to="/impressum">Impressum</Link><Link to="/datenschutz">Datenschutz</Link><a href="mailto:info@spirit-healing.tr">Kontakt</a></footer>
    </div></main>;
};
