import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { ArrowRight, Download, Play } from "lucide-react";
import { replayFunnel as funnel } from "@/content/replayFunnel";

export const LiveReplay = () => {
    const [play, setPlay] = useState(false);
    const [upcoming, setUpcoming] = useState(() => Date.now() < Date.parse(funnel.nextLiveStartsAt));
    useEffect(() => {
        const timer = window.setInterval(() => setUpcoming(Date.now() < Date.parse(funnel.nextLiveStartsAt)), 60000);
        return () => window.clearInterval(timer);
    }, []);
    return <main data-no-translate="true" className="min-h-screen bg-[#faf6ed] text-[#173c39]">
        <nav className="mx-auto flex max-w-6xl flex-wrap items-center justify-between gap-4 px-6 py-6"><Link to="/" className="font-serif text-xl">Spirit Healing</Link><Link to="/vortraege-seminare#kalender" className="text-sm underline underline-offset-4">Alle Termine</Link></nav>
        <header className="bg-[#064e51] px-6 pb-16 pt-12 text-white sm:pt-16"><div className="mx-auto max-w-5xl"><p className="text-sm font-semibold uppercase tracking-[0.2em] text-[#edcf96]">Der Live-Abend vom 6. Oktober · mit Sabine & Selcan</p><h1 className="mt-5 max-w-4xl font-serif text-4xl leading-tight sm:text-6xl">Ein Satz. Ein Blick.<br/>Und plötzlich läuft dein alter Film.</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-white/85">Wer hält in diesem Moment das Zepter? In unserem Vortrag schauen wir auf die Anteile in uns, vertraute Rollen und deine persönliche Matrix. Nimm mit uns eine neue Perspektive ein.</p><a href="#aufzeichnung" className="mt-8 inline-flex min-h-12 items-center gap-3 rounded-full bg-[#ecd197] px-7 py-4 font-bold text-[#173c39]">Zum Vortrag & Workbook<ArrowRight size={18}/></a></div></header>
        <section id="aufzeichnung" className="mx-auto max-w-5xl scroll-mt-5 px-6 py-12"><p className="text-xs font-bold uppercase tracking-[0.18em] text-[#8f702f]">Dein Einstieg</p><h2 className="mt-3 font-serif text-3xl sm:text-4xl">{funnel.title}</h2>
            <div className="mt-6 overflow-hidden rounded-3xl bg-[#123e3e] shadow-xl shadow-[#173c39]/10">{play && funnel.videoUrl ? <iframe className="aspect-video w-full" src={funnel.videoUrl} title="Aufzeichnung: Wer schreibt dein inneres Drehbuch?" allow="fullscreen; picture-in-picture" allowFullScreen referrerPolicy="no-referrer"/> : <div className="relative"><img src={funnel.image} alt="Sabine und Selcan im gemeinsamen Live-Vortrag" className="aspect-video w-full object-cover"/>{funnel.videoUrl && <button onClick={() => setPlay(true)} aria-label="Vortrag abspielen und Vimeo laden" className="absolute inset-0 flex items-center justify-center bg-black/15"><span className="flex items-center gap-3 rounded-full bg-[#faf6ed] px-6 py-4 font-bold text-[#173c39]"><Play size={22}/>Vortrag abspielen</span></button>}</div>}<div className="px-6 py-5 text-white"><p className="font-semibold">Unser erster Live-Vortrag zum 13-Wochen-Programm.</p>{!funnel.videoUrl ? <p role="status" className="mt-2 text-sm leading-6 text-white/80">Die Aufzeichnung wird gerade fertiggestellt. Hier findest du sie, sobald der Schnitt geprüft ist. Das Workbook kannst du bereits herunterladen.</p> : <p className="mt-2 text-sm leading-6 text-white/80">Beim Abspielen wird eine Verbindung zu Vimeo hergestellt. <Link className="underline" to="/datenschutz">Datenschutz</Link></p>}</div></div>
            <p className="mt-7 max-w-3xl text-lg leading-8">Du warst beim ersten Abend nicht dabei? Wir nehmen dich von Anfang an mit. Im Gespräch und in einer Meditation öffnen wir den Blick auf deine innere Welt: aus deinem Herzraum, mit deinem höheren Selbst und einer neuen Perspektive auf die Anteile in dir.</p>
        </section>
        <section id="workbook" className="mx-auto grid max-w-5xl gap-8 px-6 pb-14 md:grid-cols-[0.75fr_1.25fr] md:items-center"><div className="rounded-3xl border border-[#d7c397] bg-white p-8 shadow-lg shadow-[#173c39]/5"><p className="text-xs font-bold uppercase tracking-[0.2em] text-[#987537]">Spirit Healing · Workbook</p><h2 className="mt-8 font-serif text-4xl leading-tight">Eine neue<br/>Perspektive.</h2><p className="mt-5 leading-7 text-[#52675d]">Deine Beobachtungen.<br/>Deine Fragen.<br/>Raum zum Festhalten.</p><p className="mt-10 border-t border-[#d7c397] pt-5 text-sm">Sabine & Selcan</p></div><div><h2 className="font-serif text-3xl">Nimm eine Situation aus deinem Alltag.</h2><p className="mt-5 leading-8">Beobachte dich, während du handelst. Was verändert sich in deiner Stimme, deiner Körperhaltung oder deinem Gefühl? Welche Sätze kommen dir vertraut vor? Was berührt dich in einer Begegnung mit einem anderen Menschen?</p><p className="mt-4 leading-8">Du musst jetzt nichts lösen. Beginne mit Neugier und halte fest, was du wahrnimmst. Im Workbook findest du dafür Platz. Du kannst es am Bildschirm ausfüllen oder ausdrucken.</p><a href={funnel.workbook} download className="mt-7 inline-flex min-h-12 items-center gap-3 rounded-full bg-[#075d60] px-7 py-4 font-bold text-white"><Download size={18}/>Workbook herunterladen</a><p className="mt-3 text-sm text-[#52675d]">Kostenlos · PDF · 4 Seiten</p></div></section>
        {upcoming && <section className="bg-[#e9ede2] px-6 py-14"><div className="mx-auto max-w-5xl"><p className="text-xs font-bold uppercase tracking-[0.18em] text-[#846429]">Dienstag, 20. Oktober 2026 · 20 Uhr deutscher Zeit</p><h2 className="mt-4 max-w-3xl font-serif text-4xl leading-tight">Wir gehen mit deinen Erfahrungen eine Stufe tiefer.</h2><p className="mt-5 max-w-3xl text-lg leading-8">Was hast du beim Beobachten entdeckt? Wo hast du einen Anteil bemerkt? Welche Frage ist geblieben? Im zweiten Live holen wir euch bei euren Erfahrungen ab und gehen gemeinsam weiter. Auch wenn du beim ersten Mal nicht dabei warst, bist du willkommen.</p><Link to={funnel.nextLivePath} className="mt-7 inline-flex min-h-12 items-center gap-3 rounded-full bg-[#075d60] px-7 py-4 font-bold text-white">Zum zweiten Live<ArrowRight size={18}/></Link></div></section>}
        <footer className="mx-auto flex max-w-5xl flex-wrap gap-6 px-6 py-8 text-sm"><Link to="/impressum">Impressum</Link><Link to="/datenschutz">Datenschutz</Link><a href="mailto:info@spirit-healing.tr">info@spirit-healing.tr</a></footer>
    </main>;
};
